import React, { useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

export default function StaffChatWorkspace({ user, schoolCode }) {
  const [staff, setStaff] = useState([]), [threads, setThreads] = useState([]), [selected, setSelected] = useState(null), [messages, setMessages] = useState([]), [text, setText] = useState(""), [sending, setSending] = useState(false);
  const creds = { school_code: schoolCode, caller_username: user?.username, caller_password: user?.password || localStorage.getItem("userPassword") || "", caller_email: user?.email || "", caller_sso: Boolean(user?.sso || user?.email) };
  const loadThreads = async () => { const [people, result] = await Promise.all([base44.functions.invoke("manageStaffMessages", { action: "staff", ...creds }), base44.functions.invoke("manageStaffMessages", { action: "threads", ...creds })]); setStaff((people.data?.staff || []).filter((person) => person.id !== user?.id)); setThreads(result.data?.threads || []); };
  const openThread = async (person) => { setSelected(person); const action = person.id === "support" ? "support_thread" : "thread"; const payload = person.id === "support" ? { action, ...creds } : { action, recipient_id: person.id, ...creds }; const result = await base44.functions.invoke("manageStaffMessages", payload); setMessages(result.data?.messages || []); if (person.id !== "support") loadThreads(); };
  useEffect(() => { if (schoolCode && user?.id) loadThreads(); }, [schoolCode, user?.id]);
  const send = async () => { setSending(true); const payload = selected.id === "support" ? { action: "support_request", content: text, current_path: window.location.pathname, ...creds } : { action: "send", recipient_id: selected.id, content: text, ...creds }; const result = await base44.functions.invoke("manageStaffMessages", payload); setSending(false); if (result.data?.success) { setText(""); openThread(selected); } };
  const visiblePeople = [{ id: "support", full_name: "Support", preview: "Contact administrators for help" }, ...threads.map((thread) => ({ id: thread.person_id, full_name: thread.person_name, preview: thread.content, unread: thread.unread })), ...staff.filter((person) => !threads.some((thread) => thread.person_id === person.id))];
  return <div className="grid min-h-[560px] overflow-hidden rounded-xl border border-slate-200 bg-white md:grid-cols-[280px_1fr]"><aside className="border-b border-slate-200 md:border-b-0 md:border-r"><div className="border-b border-slate-100 p-4"><p className="font-semibold text-slate-900">Staff messages</p><p className="mt-1 text-xs text-slate-500">Private conversations with colleagues</p></div><div className="max-h-[480px] overflow-y-auto p-2">{visiblePeople.map((person) => <button key={person.id} onClick={() => openThread(person)} className={`relative w-full rounded-lg p-3 text-left ${selected?.id === person.id ? "bg-slate-100" : "hover:bg-slate-50"}`}><p className="truncate text-sm font-medium text-slate-800">{person.full_name}</p>{person.preview && <p className="mt-1 truncate text-xs text-slate-500">{person.preview}</p>}{person.unread > 0 && <span className="absolute right-3 top-3 rounded-full bg-rose-700 px-1.5 py-0.5 text-[10px] font-bold text-white">{person.unread}</span>}</button>)}{!visiblePeople.length && <p className="p-4 text-center text-sm text-slate-400">No colleagues available.</p>}</div></aside><section className="flex min-h-[420px] flex-col">{selected ? <><div className="border-b border-slate-100 p-4"><p className="font-semibold text-slate-900">{selected.full_name}</p></div><div className="flex-1 space-y-3 overflow-y-auto bg-slate-50 p-4">{messages.map((message) => <div key={message.id} className={`flex ${message.sender_id === user.id ? "justify-end" : "justify-start"}`}><div className={`max-w-[80%] rounded-2xl px-3 py-2 text-sm ${message.sender_id === user.id ? "bg-slate-900 text-white" : "bg-white text-slate-700 shadow-sm"}`}><p className="whitespace-pre-wrap">{message.content}</p><p className={`mt-1 text-[10px] ${message.sender_id === user.id ? "text-white/55" : "text-slate-400"}`}>{new Date(message.created_date).toLocaleString()}</p></div></div>)}</div><div className="border-t border-slate-100 p-3"><Textarea value={text} onChange={(event) => setText(event.target.value)} placeholder={`Message ${selected.full_name}…`} className="min-h-20" /><div className="mt-2 flex justify-end"><Button disabled={sending || !text.trim()} onClick={send}>{sending ? "Sending…" : "Send"}</Button></div></div></> : <div className="flex flex-1 items-center justify-center p-8 text-sm text-slate-400">Choose a colleague to start a conversation.</div>}</section></div>;
}