import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export default function DetentionAssignmentDialog({ open, onOpenChange, schoolCode, schoolName, teachers, startDate, onSaved }) {
  const [form, setForm] = useState({ teacher_id: "", day_of_week: "Monday", start_time: "15:00", end_time: "16:00", room: "" }); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const save = async () => { setError(""); if (!form.teacher_id) return setError("Choose a teacher."); if (form.end_time <= form.start_time) return setError("End time must be after start time."); setSaving(true); try { const teacher = teachers.find((item) => item.id === form.teacher_id); const className = `Detention · ${form.day_of_week}`; const detentionClass = await base44.entities.Class.create({ class_name: className, school_code: schoolCode, school_name: schoolName || "", subject: "Detention", teacher_name: teacher.full_name, status: "active", sessions_per_week: 1 }); const schedule = await base44.entities.ClassSchedule.create({ class_id: detentionClass.id, class_name: className, school_code: schoolCode, teacher_id: teacher.id, teacher_name: teacher.full_name, room: form.room, day_of_week: form.day_of_week, start_time: form.start_time, end_time: form.end_time, recurrence_type: "weekly", recurrence_weeks: 1, start_date: startDate }); await base44.entities.TeacherClass.create({ teacher_id: teacher.id, teacher_name: teacher.full_name, class_id: detentionClass.id, role: "Primary Teacher", school_code: schoolCode }); onSaved?.(schedule); onOpenChange(false); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Assign weekly detention</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Teacher</Label><select value={form.teacher_id} onChange={(event) => setForm({ ...form, teacher_id: event.target.value })} className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Choose teacher</option>{[...teachers].sort((a, b) => (a.full_name || a.username || "").localeCompare(b.full_name || b.username || "")).map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.full_name}</option>)}</select></div><div className="grid grid-cols-3 gap-3"><div><Label>Day</Label><select value={form.day_of_week} onChange={(event) => setForm({ ...form, day_of_week: event.target.value })} className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm">{["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"].map((day) => <option key={day}>{day}</option>)}</select></div><div><Label>Start</Label><Input type="time" value={form.start_time} onChange={(event) => setForm({ ...form, start_time: event.target.value })} className="mt-1" /></div><div><Label>End</Label><Input type="time" value={form.end_time} onChange={(event) => setForm({ ...form, end_time: event.target.value })} className="mt-1" /></div></div><div><Label>Room</Label><Input value={form.room} onChange={(event) => setForm({ ...form, room: event.target.value })} placeholder="Optional" className="mt-1" /></div>{error && <p className="text-sm text-destructive">{error}</p>}</div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={save} disabled={saving}>{saving ? "Assigning…" : "Assign detention"}</Button></DialogFooter></DialogContent></Dialog>;
}