import React, { useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export default function DetentionDialog({ open, onOpenChange, classId, students, user, onSaved }) {
  const [studentId, setStudentId] = useState(""); const [staff, setStaff] = useState([]); const [staffId, setStaffId] = useState(""); const [date, setDate] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!open) return; setStudentId(""); setDate(""); setStaffId(user?.id || ""); setError(""); base44.functions.invoke("manageClassCovers", { action: "list_colleagues", school_code: user?.school_code, caller_username: user?.username, caller_password: user?.password || localStorage.getItem("userPassword") || "", caller_email: user?.email || "", caller_sso: Boolean(user?.sso || user?.email) }).then((res) => setStaff([{ id: user?.id, full_name: user?.full_name || user?.username }, ...(res.data?.colleagues || [])])); }, [open, user]);
  const save = async () => { setError(""); if (!studentId || !staffId || !date) return setError("Choose a student, staff member and date."); setSaving(true); try { const result = await base44.functions.invoke("manageDetentions", { student_id: studentId, source_class_id: classId, staff_id: staffId, date, caller_username: user?.username, caller_password: user?.password || localStorage.getItem("userPassword") || "", caller_email: user?.email || "", caller_sso: Boolean(user?.sso || user?.email) }); if (!result.data?.success) throw new Error(result.data?.error || "Detention could not be scheduled"); const notification = await base44.functions.invoke("manageParentConversations", { action: "detention_notification", student_id: studentId, detention_date: date, detention_start_time: result.data.session.start_time, caller_username: user?.username, caller_password: user?.password || localStorage.getItem("userPassword") || "", caller_email: user?.email || "", caller_sso: Boolean(user?.sso || user?.email) }); if (!notification.data?.success) throw new Error(notification.data?.error || "Parent notification could not be sent"); onSaved?.(); onOpenChange(false); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Assign detention</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Student</Label><select value={studentId} onChange={(e) => setStudentId(e.target.value)} className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Choose student</option>{students.map((student) => <option key={student.student_id} value={student.student_id}>{student.student_name}</option>)}</select></div><div><Label>Detention staff member</Label><select value={staffId} onChange={(e) => setStaffId(e.target.value)} className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm">{staff.map((member) => <option key={member.id} value={member.id}>{member.full_name}</option>)}</select></div><div><Label>Date</Label><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} min={new Date().toISOString().slice(0, 10)} className="mt-1" /></div><p className="text-xs text-slate-500">The session starts at the school end time unless a manager has set a detention time.</p>{error && <p className="text-sm text-destructive">{error}</p>}</div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={save} disabled={saving}>{saving ? "Scheduling…" : "Assign detention"}</Button></DialogFooter></DialogContent></Dialog>;
}