import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Upload } from "lucide-react";

export default function SubmissionDialog({ assignment, user, onOpenChange, onSaved }) {
  const [file, setFile] = useState(null); const [text, setText] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const submit = async () => { setError(""); if (!file && !text.trim()) { setError("Upload a file or add a typed response."); return; } setSaving(true); try { const upload = file ? await base44.integrations.Core.UploadFile({ file }) : {}; const res = await base44.functions.invoke("manageAssignments", { action: "submit", caller_username: user.username, caller_password: user.password || localStorage.getItem("userPassword") || "", assignment_id: assignment.id, file_url: upload.file_url || "", file_name: file?.name || "", submission_text: text }); if (!res.data?.success) throw new Error(res.data?.error); onSaved(); onOpenChange(false); } catch (e) { setError(e.message || "Unable to submit assignment"); } finally { setSaving(false); } };
  return <Dialog open={!!assignment} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Submit: {assignment?.title}</DialogTitle></DialogHeader><div className="space-y-4"><div><label className="text-sm font-medium text-slate-700">Upload assignment</label><Input type="file" onChange={(e) => setFile(e.target.files?.[0] || null)} className="mt-1.5" /></div><div><label className="text-sm font-medium text-slate-700">Typed response for AI similarity check</label><Textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="Paste your written response here to receive a similarity-risk estimate." className="mt-1.5 min-h-28" /></div><p className="text-xs text-slate-500">The AI score is a similarity-risk estimate, not a definitive plagiarism finding.</p>{error && <p className="text-sm text-rose-600">{error}</p>}<Button onClick={submit} disabled={saving} className="w-full"> <Upload className="w-4 h-4 mr-1.5" />{saving ? "Checking and submitting…" : "Submit assignment"}</Button></div></DialogContent></Dialog>;
}