import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Upload } from "lucide-react";

export default function SubmissionDialog({ assignment, user, onOpenChange, onSaved }) {
  const [file, setFile] = useState(null); const [aiReportFile, setAiReportFile] = useState(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const submit = async () => { setError(""); if (!file) { setError("Upload your assignment submission."); return; } setSaving(true); try { const [upload, reportUpload] = await Promise.all([base44.integrations.Core.UploadFile({ file }), aiReportFile ? base44.integrations.Core.UploadFile({ file: aiReportFile }) : Promise.resolve(null)]); const res = await base44.functions.invoke("manageAssignments", { action: "submit", caller_username: user.username, caller_password: user.password || localStorage.getItem("userPassword") || "", assignment_id: assignment.id, file_url: upload.file_url, file_name: file.name, ai_report_file_url: reportUpload?.file_url || "", ai_report_file_name: aiReportFile?.name || "" }); if (!res.data?.success) throw new Error(res.data?.error); onSaved(); onOpenChange(false); } catch (e) { setError(e.message || "Unable to submit assignment"); } finally { setSaving(false); } };
  return <Dialog open={!!assignment} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Submit: {assignment?.title}</DialogTitle></DialogHeader><div className="space-y-4"><div><label className="text-sm font-medium text-slate-700">Assignment Submission</label><Input type="file" required onChange={(e) => setFile(e.target.files?.[0] || null)} className="mt-1.5" /></div>{assignment?.enable_ai_plagiarism_report && <div><label className="text-sm font-medium text-slate-700">AI/Plagiarism Report <span className="font-normal text-slate-400">(optional)</span></label><Input type="file" onChange={(e) => setAiReportFile(e.target.files?.[0] || null)} className="mt-1.5" /></div>}{error && <p className="text-sm text-rose-600">{error}</p>}<Button onClick={submit} disabled={saving} className="w-full"><Upload className="w-4 h-4 mr-1.5" />{saving ? "Uploading…" : "Submit assignment"}</Button></div></DialogContent></Dialog>;
}