import React, { useCallback, useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Checkbox } from "@/components/ui/checkbox";
import { ClipboardList, Plus, ExternalLink } from "lucide-react";

export default function TeacherAssignments({ classInfo, user }) {
  const [assignments, setAssignments] = useState([]); const [submissions, setSubmissions] = useState([]); const [open, setOpen] = useState(false); const [viewing, setViewing] = useState(null); const [form, setForm] = useState({ title: "", instructions: "", deadline: "", enable_ai_plagiarism_report: false }); const creds = { caller_username: user?.username, caller_password: user?.password || localStorage.getItem("userPassword") || "", caller_email: user?.email || "", caller_sso: Boolean(user?.sso || user?.email) };
  const load = useCallback(async () => { if (!classInfo?.id) return; const res = await base44.functions.invoke("manageAssignments", { action: "teacher_list", ...creds, class_id: classInfo.id }); setAssignments(res.data?.assignments || []); setSubmissions(res.data?.submissions || []); }, [classInfo?.id, user]);
  useEffect(() => { load(); }, [load]);
  const create = async () => { const res = await base44.functions.invoke("manageAssignments", { action: "create", ...creds, assignment: { ...form, class_id: classInfo.id, class_name: classInfo.class_name } }); if (res.data?.success) { setOpen(false); setForm({ title: "", instructions: "", deadline: "", enable_ai_plagiarism_report: false }); load(); } };
  const view = async (submission) => { const res = await base44.functions.invoke("manageAssignments", { action: "view_submission", ...creds, submission_id: submission.id }); setViewing(res.data?.submission || submission); load(); };
  return <><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => setOpen(true)}><Plus className="w-4 h-4 mr-1" />New assignment</Button></div><div className="grid gap-3">{assignments.map((item) => <div key={item.id} className="rounded-xl border border-slate-200 p-4"><h3 className="font-semibold text-slate-800">{item.title}</h3><p className="text-xs text-slate-500 mt-1">Due {new Date(item.deadline).toLocaleString()} · {submissions.filter((sub) => sub.assignment_id === item.id).length} submitted</p>{submissions.filter((sub) => sub.assignment_id === item.id).map((sub) => <button key={sub.id} onClick={() => view(sub)} className="mt-2 text-left w-full rounded-lg bg-slate-50 px-3 py-2 text-sm text-slate-700 hover:bg-slate-100">{sub.student_name} · {sub.ai_report_file_url ? "AI/Plagiarism Report attached" : "No report attached"} · {sub.status === "viewed" ? "Viewed" : "New"}</button>)}</div>)}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Create assignment</DialogTitle></DialogHeader><div className="space-y-3"><Input placeholder="Assignment title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><Textarea placeholder="Instructions" value={form.instructions} onChange={(e) => setForm({ ...form, instructions: e.target.value })} /><Input type="datetime-local" value={form.deadline} onChange={(e) => setForm({ ...form, deadline: e.target.value })} /><label className="flex items-center gap-2 text-sm text-slate-700"><Checkbox checked={form.enable_ai_plagiarism_report} onCheckedChange={(checked) => setForm({ ...form, enable_ai_plagiarism_report: checked === true })} />Enable optional AI/Plagiarism Report upload</label><Button onClick={create} className="w-full">Post assignment</Button></div></DialogContent></Dialog><Dialog open={!!viewing} onOpenChange={(openState) => !openState && setViewing(null)}><DialogContent><DialogHeader><DialogTitle>{viewing?.student_name}'s submission</DialogTitle></DialogHeader><div className="space-y-3 text-sm"><p className="font-medium text-slate-800">Uploaded files</p>{viewing?.submission_text && <p className="whitespace-pre-wrap rounded-lg bg-slate-50 p-3">{viewing.submission_text}</p>}{viewing?.file_url && <a className="inline-flex items-center text-blue-700" href={viewing.file_url} target="_blank" rel="noreferrer"><ExternalLink className="w-4 h-4 mr-1" />Open Assignment Submission</a>}{viewing?.ai_report_file_url && <a className="inline-flex items-center text-blue-700" href={viewing.ai_report_file_url} target="_blank" rel="noreferrer"><ExternalLink className="w-4 h-4 mr-1" />Open AI/Plagiarism Report</a>}</div></DialogContent></Dialog></>;
}