import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

const areas = ["academic", "attendance", "behaviour", "wellbeing", "other"];
export default function InterventionManager({ student, interventions, user, onSaved }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ title: "", area: "academic", goal: "", strategy: "", review_date: "" });
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const save = async (event) => { event.preventDefault(); setSaving(true); const res = await base44.functions.invoke("manageStudents", { action: "save_intervention", caller_username: user?.username, caller_password: user?.password || localStorage.getItem("userPassword") || "", caller_email: user?.email || "", caller_sso: Boolean(user?.sso || user?.email), student_id: student.id, data: form }); if (res.data?.success) { onSaved(res.data.intervention); setOpen(false); setForm({ title: "", area: "academic", goal: "", strategy: "", review_date: "" }); } setSaving(false); };
  const setStatus = async (item, status) => { const res = await base44.functions.invoke("manageStudents", { action: "save_intervention", caller_username: user?.username, caller_password: user?.password || localStorage.getItem("userPassword") || "", caller_email: user?.email || "", caller_sso: Boolean(user?.sso || user?.email), student_id: student.id, data: { ...item, status } }); if (res.data?.success) onSaved(res.data.intervention); };
  return <div className="space-y-3"><div className="flex items-center justify-between"><p className="text-sm text-slate-500">Active plans and support actions for this student.</p><Button size="sm" onClick={() => setOpen((value) => !value)}>{open ? "Cancel" : "Add intervention"}</Button></div>{open && <form onSubmit={save} className="grid grid-cols-1 gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4"><Input required value={form.title} onChange={(e) => update("title", e.target.value)} placeholder="Intervention title" /><select value={form.area} onChange={(e) => update("area", e.target.value)} className="h-9 rounded-md border border-slate-200 bg-white px-3 text-sm">{areas.map((area) => <option key={area}>{area}</option>)}</select><Textarea value={form.goal} onChange={(e) => update("goal", e.target.value)} placeholder="Student goal" /><Textarea value={form.strategy} onChange={(e) => update("strategy", e.target.value)} placeholder="Support strategy" /><Input type="date" value={form.review_date} onChange={(e) => update("review_date", e.target.value)} /><Button disabled={saving} type="submit">{saving ? "Saving..." : "Save intervention"}</Button></form>}<div className="space-y-2">{interventions.length ? interventions.map((item) => <div key={item.id} className="rounded-xl border border-slate-200 p-3"><div className="flex justify-between gap-3"><p className="font-medium text-slate-800">{item.title}</p><select value={item.status} onChange={(e) => setStatus(item, e.target.value)} className="rounded border border-slate-200 bg-white px-2 py-1 text-xs font-medium capitalize text-blue-700"><option value="active">active</option><option value="monitoring">monitoring</option><option value="completed">completed</option><option value="closed">closed</option></select></div><p className="mt-1 text-sm text-slate-600">{item.goal || item.strategy || "No goal recorded."}</p>{item.review_date && <p className="mt-2 text-xs text-slate-400">Review: {item.review_date}</p>}</div>) : <p className="py-4 text-center text-sm text-slate-400">No interventions recorded.</p>}</div></div>;
}