import React, { useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import StudentSupportPlansEditor from "@/components/student/StudentSupportPlansEditor";

const fields = [["student_name", "Student name"], ["student_number", "Student number"], ["grade_level", "Grade level"], ["homeroom", "Homeroom"], ["state_student_id", "State student ID"], ["address_line_1", "Address"], ["city", "City"], ["state", "State"], ["postal_code", "Postal code"]];

export default function StudentProfileEditDialog({ open, onOpenChange, student, user, onSaved }) {
  const [form, setForm] = useState({}), [saving, setSaving] = useState(false), [error, setError] = useState("");
  useEffect(() => { if (open) setForm(student || {}); }, [open, student]);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const isElementaryOrMiddle = ["K", "KG", "Pre-K"].includes(String(form.grade_level || "").toUpperCase()) || Number(form.grade_level) <= 8;
  const save = async () => { setSaving(true); setError(""); const res = await base44.functions.invoke("manageStudents", { action: "update", caller_username: user?.username, caller_password: user?.password || localStorage.getItem("userPassword") || "", caller_email: user?.email || "", caller_sso: Boolean(user?.sso || user?.email), student_id: student.id, data: form }); setSaving(false); if (res.data?.success) { onSaved(res.data.student); onOpenChange(false); } else setError(res.data?.error || "Profile could not be saved."); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Edit student profile</DialogTitle></DialogHeader><div className="grid gap-4 sm:grid-cols-2">{fields.map(([key, label]) => <div key={key}><Label>{label}</Label><Input className="mt-1" value={form[key] || ""} disabled={key === "student_number"} onChange={(event) => set(key, event.target.value)} /></div>)}<div><Label>Status</Label><select className="mt-1 h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm" value={form.status || "active"} onChange={(event) => set("status", event.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option><option value="transferred">Transferred</option></select></div><div><Label>Lunch status</Label><select className="mt-1 h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm" value={form.lunch_status || ""} onChange={(event) => set("lunch_status", event.target.value)}><option value="">Not recorded</option><option value="Free">Free</option><option value="Reduced">Reduced</option><option value="Paid">Paid</option></select></div>{isElementaryOrMiddle && <div><Label>Transportation</Label><select className="mt-1 h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm" value={form.transportation || ""} onChange={(event) => set("transportation", event.target.value)}><option value="">Not recorded</option><option value="Bus Rider">Bus Rider</option><option value="Pickup">Pickup</option></select></div>}<div className="sm:col-span-2"><Label>Medical notes</Label><Textarea className="mt-1" value={form.medical_notes || ""} onChange={(event) => set("medical_notes", event.target.value)} /></div><div className="sm:col-span-2"><Label>Custody or release alerts</Label><Textarea className="mt-1" value={form.custody_alerts || ""} onChange={(event) => set("custody_alerts", event.target.value)} /></div>{user?.role === "manager" && <StudentSupportPlansEditor plans={form.support_plans || []} onChange={(plans) => set("support_plans", plans)} />}</div>{error && <p className="text-sm text-rose-600">{error}</p>}<DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={saving || !form.student_name?.trim()} onClick={save}>{saving ? "Saving…" : "Save changes"}</Button></DialogFooter></DialogContent></Dialog>;
}