import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Image } from "@/components/ui/image";

export default function SchoolBrandingSettings({ school, credentials, onSaved }) {
  const [file, setFile] = useState(null); const [headerColor, setHeaderColor] = useState(school?.header_color || "#0B1530"); const [menuTextColor, setMenuTextColor] = useState(school?.menu_text_color || "#FFFFFF"); const [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); const upload = file ? await base44.integrations.Core.UploadFile({ file }) : {}; const res = await base44.functions.invoke("manageSchoolBranding", { action: "save", school_code: school?.school_code, system_code: school?.system_code, school_name: school?.school_name, logo_url: upload.file_url || school?.logo_url || "", header_color: headerColor, menu_text_color: menuTextColor, ...credentials }); if (res.data?.success) onSaved(res.data.branding); setSaving(false); };
  return <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">School branding</h2><p className="mt-1 text-sm text-slate-500">Set the logo and colors shown to staff in your school workspace.</p><div className="mt-4 space-y-4"><div className="flex items-center gap-4">{school?.logo_url && <Image src={school.logo_url} alt="School logo" className="h-12 w-20 rounded-md border border-slate-200 bg-white" fittingType="fit" />}<Input type="file" accept="image/*" onChange={(e) => setFile(e.target.files?.[0] || null)} /></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Header color<Input type="color" value={headerColor} onChange={(e) => setHeaderColor(e.target.value)} className="mt-1 h-10 p-1" /></label><label className="text-sm font-medium text-slate-700">Menu text color<Input type="color" value={menuTextColor} onChange={(e) => setMenuTextColor(e.target.value)} className="mt-1 h-10 p-1" /></label></div><Button onClick={save} disabled={saving}>{saving ? "Saving…" : "Save school branding"}</Button></div></section>;
}