import React, { useEffect, useState } from "react";
import { Trophy, UsersRound, CalendarClock } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { useSchool } from "@/lib/SchoolContext";
import AthleticsTeamForm from "@/components/athletics/AthleticsTeamForm";
import AthleticsEventForm from "@/components/athletics/AthleticsEventForm";
import AthleticsRosterManager from "@/components/athletics/AthleticsRosterManager";
import AthleticsAbsenceList from "@/components/athletics/AthleticsAbsenceList";

export default function Athletics() {
  const { school, user } = useSchool(); const schoolCode = school?.school_code || user?.school_code;
  const [data, setData] = useState({ teams: [], members: [], events: [], students: [] }); const [loading, setLoading] = useState(true);
  const load = async () => { if (!schoolCode) return; setLoading(true); const [teams, members, events, students] = await Promise.all([base44.entities.AthleticsTeam.filter({ school_code: schoolCode }), base44.entities.AthleticsTeamMember.filter({ school_code: schoolCode }), base44.entities.AthleticsEvent.filter({ school_code: schoolCode }), base44.entities.Student.filter({ school_code: schoolCode })]); setData({ teams, members, events, students }); setLoading(false); };
  useEffect(() => { load(); }, [schoolCode]);
  if (loading) return <div className="h-64 animate-pulse rounded-xl bg-slate-100" />;
  return <div className="space-y-7"><div><div className="flex items-center gap-2"><Trophy className="h-6 w-6 text-rose-700" /><h1 className="text-2xl font-bold text-slate-900">Athletics</h1></div><p className="mt-1 text-sm text-slate-500">Manage teams and give teachers a clear view of students who will be out of class.</p></div><section className="space-y-3"><div className="flex items-center gap-2"><UsersRound className="h-4 w-4 text-slate-500" /><h2 className="font-semibold text-slate-900">Teams and rosters</h2></div><AthleticsTeamForm schoolCode={schoolCode} user={user} onCreated={(team) => setData((current) => ({ ...current, teams: [...current.teams, team] }))} /><div className="grid gap-4 lg:grid-cols-2">{data.teams.map((team) => <AthleticsRosterManager key={team.id} team={team} students={data.students} members={data.members} schoolCode={schoolCode} onAdded={(newMembers) => setData((current) => ({ ...current, members: [...current.members, ...(Array.isArray(newMembers) ? newMembers : [newMembers])] }))} onRemoved={(memberId) => setData((current) => ({ ...current, members: current.members.filter((member) => member.id !== memberId) }))} />)}</div>{!data.teams.length && <p className="text-sm text-slate-500">Create a team to begin adding athletes.</p>}</section><section className="space-y-3"><div className="flex items-center gap-2"><CalendarClock className="h-4 w-4 text-slate-500" /><h2 className="font-semibold text-slate-900">Athletics schedule</h2></div><AthleticsEventForm schoolCode={schoolCode} teams={data.teams} onCreated={(event) => setData((current) => ({ ...current, events: [...current.events, event] }))} /></section><section className="space-y-3"><h2 className="font-semibold text-slate-900">Upcoming student absences</h2><p className="text-sm text-slate-500">Use this view to plan classroom work around athletics commitments.</p><AthleticsAbsenceList events={data.events} members={data.members} /></section></div>;
}