import React, { useCallback, useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { useSchool } from "@/lib/SchoolContext";
import AttendanceRecordsTable from "@/components/attendance-review/AttendanceRecordsTable";
import EditAttendanceRecordDialog from "@/components/attendance-review/EditAttendanceRecordDialog";
import { Input } from "@/components/ui/input";

export default function AttendanceReview() {
  const { user, activeSchool, canManageStaff } = useSchool();
  const [records, setRecords] = useState([]); const [loading, setLoading] = useState(false); const [editing, setEditing] = useState(null); const [saving, setSaving] = useState(false); const [search, setSearch] = useState(""); const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const payload = { caller_username: user?.username, caller_password: user?.password || localStorage.getItem("userPassword") || "", caller_email: user?.email || "", caller_sso: Boolean(user?.sso || user?.email), school_code: activeSchool?.school_code };
  const load = useCallback(async () => { if (search.trim().length < 2 || !activeSchool?.school_code) { setRecords([]); return; } setLoading(true); const response = await base44.functions.invoke("manageAttendanceReview", { action: "search", query: search, date, ...payload }); setRecords(response.data?.records || []); setLoading(false); }, [activeSchool?.school_code, date, search, user?.id]);
  useEffect(() => { load(); }, [load]);
  const save = async (changes) => { setSaving(true); const upload = changes.file ? await base44.integrations.Core.UploadFile({ file: changes.file }) : null; const response = await base44.functions.invoke("manageAttendanceReview", { action: "save", record_id: editing.id, student_id: editing.student_id, class_id: editing.class_id, schedule_id: editing.schedule_id, date: editing.date, status: changes.status, excused_reason: changes.excused_reason, attachment_file_url: upload?.file_url, attachment_file_name: changes.file?.name, ...payload }); if (response.data?.success) { setEditing(null); await load(); } setSaving(false); };
  if (!canManageStaff) return <p className="py-16 text-center text-sm text-slate-400">School manager access is required.</p>;
  return <div className="space-y-5"><div><h2 className="text-lg font-bold text-slate-900">Attendance Review</h2><p className="text-sm text-slate-500">Search a student or class to review the day’s scheduled attendance.</p></div><div className="flex flex-wrap gap-3 rounded-xl border border-slate-200 bg-white p-4"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search student or class" className="w-64" autoFocus /><Input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="w-44" /></div><div className="rounded-xl border border-slate-200 bg-white">{search.trim().length < 2 ? <p className="p-12 text-center text-sm text-slate-400">Search for a student or class to view attendance.</p> : loading ? <p className="p-8 text-center text-sm text-slate-400">Loading scheduled classes…</p> : <AttendanceRecordsTable records={records} onEdit={setEditing} />}</div><EditAttendanceRecordDialog record={editing} onClose={() => setEditing(null)} onSave={save} saving={saving} /></div>;
}