import React, { useCallback, useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { useSchool } from "@/lib/SchoolContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import SectionCard from "@/components/SectionCard";
import { Send, Siren } from "lucide-react";

export default function Messages() {
  const { user, school, canManageStaff } = useSchool();
  const [staff, setStaff] = useState([]), [messages, setMessages] = useState([]), [recipient, setRecipient] = useState(""), [text, setText] = useState(""), [alertTitle, setAlertTitle] = useState(""), [alertText, setAlertText] = useState(""), [targets, setTargets] = useState([]), [sending, setSending] = useState(false);
  const creds = { school_code: school?.school_code, caller_username: user?.username, caller_password: user?.password || localStorage.getItem("userPassword") || "", caller_email: user?.email || "", caller_sso: Boolean(user?.sso || user?.email) };
  const load = useCallback(async () => { if (!school?.school_code) return; const [inbox, people] = await Promise.all([base44.functions.invoke("manageStaffMessages", { action: "inbox", ...creds }), base44.functions.invoke("manageStaffMessages", { action: "staff", ...creds })]); setMessages(inbox.data?.messages || []); setStaff((people.data?.staff || []).filter((person) => person.id !== user?.id)); }, [school?.school_code, user?.id]);
  useEffect(() => { load(); }, [load]);
  const send = async (action) => { setSending(true); const payload = action === "send" ? { action, recipient_id: recipient, content: text } : { action, title: alertTitle, content: alertText, recipient_ids: targets }; const result = await base44.functions.invoke("manageStaffMessages", { ...payload, ...creds }); if (result.data?.success) { setText(""); setAlertTitle(""); setAlertText(""); setTargets([]); load(); } setSending(false); };
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-slate-900">Messages</h1><p className="mt-1 text-sm text-slate-500">Send private messages to colleagues and review your inbox.</p></div><SectionCard title="New message" icon={Send}><div className="space-y-3"><select value={recipient} onChange={(e) => setRecipient(e.target.value)} className="w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm"><option value="">Choose a colleague…</option>{staff.map((person) => <option key={person.id} value={person.id}>{person.full_name}</option>)}</select><Textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="Write a message…" /><Button disabled={sending || !recipient || !text.trim()} onClick={() => send("send")}>Send message</Button></div></SectionCard>{canManageStaff && <SectionCard title="Send school alert" subtitle="Alerts appear as a popup for recipients" icon={Siren}><div className="space-y-3"><Input value={alertTitle} onChange={(e) => setAlertTitle(e.target.value)} placeholder="Alert title" /><Textarea value={alertText} onChange={(e) => setAlertText(e.target.value)} placeholder="Alert details" /><div><Label>Recipients</Label><select multiple value={targets} onChange={(e) => setTargets(Array.from(e.target.selectedOptions, (option) => option.value))} className="mt-1 h-28 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm">{staff.map((person) => <option key={person.id} value={person.id}>{person.full_name}</option>)}</select><p className="mt-1 text-xs text-slate-400">Leave unselected to alert every teacher.</p></div><Button disabled={sending || !alertTitle.trim() || !alertText.trim()} onClick={() => send("alert")}>Send alert</Button></div></SectionCard>}<SectionCard title="Inbox"><div className="space-y-2">{messages.length ? messages.map((message) => <div key={message.id} className={`rounded-xl border p-4 ${message.type === "alert" ? "border-amber-200 bg-amber-50" : "border-slate-200"}`}><div className="flex justify-between gap-4"><div><p className="font-semibold text-slate-800">{message.title || `Message from ${message.sender_name}`}</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{message.content}</p><p className="mt-2 text-xs text-slate-400">{message.sender_name} · {new Date(message.created_date).toLocaleString()}</p></div>{message.type === "alert" && <span className="text-xs font-semibold text-amber-700">Alert</span>}</div></div>) : <p className="py-6 text-center text-sm text-slate-400">No messages yet.</p>}</div></SectionCard></div>;
}