import React, { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import SubmissionDialog from "@/components/assignments/SubmissionDialog";
import { ArrowLeft, ClipboardCheck } from "lucide-react";

export default function MyAssignments() {
  const navigate = useNavigate(); const [user, setUser] = useState(null); const [data, setData] = useState({ assignments: [], submissions: [] }); const [selected, setSelected] = useState(null);
  const load = useCallback(async (student) => { const response = await base44.functions.invoke("manageAssignments", { action: "student_list", caller_username: student.username, caller_password: student.password || localStorage.getItem("userPassword") || "" }); setData({ assignments: response.data?.assignments || [], submissions: response.data?.submissions || [] }); }, []);
  useEffect(() => { const session = JSON.parse(localStorage.getItem("userSession") || "null"); if (!session?.user || session.user.role !== "student") { navigate("/login", { replace: true }); return; } setUser(session.user); load(session.user); }, [load, navigate]);
  if (!user) return null;
  return <div className="min-h-screen bg-slate-50 p-4 md:p-8"><main className="mx-auto max-w-3xl space-y-6"><Button variant="ghost" size="sm" onClick={() => navigate("/my-student")}><ArrowLeft className="w-4 h-4" />Back to dashboard</Button><div><h1 className="text-xl font-bold text-slate-900">My Assignments</h1><p className="text-sm text-slate-500">Review and submit your classwork.</p></div>{data.assignments.map((assignment) => { const submission = data.submissions.find((item) => item.assignment_id === assignment.id); return <div key={assignment.id} className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">{assignment.title}</h2><p className="mt-1 text-sm text-slate-600">{assignment.class_name} · Due {new Date(assignment.deadline).toLocaleString()}</p>{assignment.instructions && <p className="mt-3 whitespace-pre-wrap text-sm text-slate-600">{assignment.instructions}</p>}{submission?.grade_released && <div className="mt-4 rounded-lg bg-emerald-50 p-4"><p className="font-semibold text-emerald-900">Grade: {submission.grade_percentage}% · {submission.letter_grade}</p>{submission.feedback && <p className="mt-2 whitespace-pre-wrap text-sm text-emerald-800">{submission.feedback}</p>}</div>}<div className="mt-4"><Button size="sm" variant={submission ? "outline" : "default"} onClick={() => setSelected(assignment)}>{submission ? "Update submission" : "Submit assignment"}</Button></div></div>; })}{data.assignments.length === 0 && <div className="py-16 text-center text-sm text-slate-500"><ClipboardCheck className="mx-auto mb-3 w-9 h-9 text-slate-300" />No assignments are available.</div>}<SubmissionDialog assignment={selected} user={user} onOpenChange={(open) => !open && setSelected(null)} onSaved={() => load(user)} /></main></div>;
}