import React, { useCallback, useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { useSchool } from "@/lib/SchoolContext";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import SectionCard from "@/components/SectionCard";

export default function ParentConversations() {
  const { user, school } = useSchool();
  const [conversations, setConversations] = useState([]), [active, setActive] = useState(null), [messages, setMessages] = useState([]), [reply, setReply] = useState(""), [sending, setSending] = useState(false);
  const credentials = { caller_username: user?.username, caller_password: user?.password || localStorage.getItem("userPassword") || "", caller_email: user?.email || "", caller_sso: Boolean(user?.sso || user?.email) };
  const load = useCallback(async () => { if (!user) return; const res = await base44.functions.invoke("manageParentConversations", { action: "list", ...credentials, school_code: school?.school_code }); setConversations(res.data?.conversations || []); }, [user?.id, school?.school_code]);
  useEffect(() => { load(); }, [load]);
  const open = async (item) => { const res = await base44.functions.invoke("manageParentConversations", { action: "thread", conversation_id: item.id, ...credentials }); if (res.data?.success) { setActive(res.data.conversation); setMessages(res.data.messages); load(); } };
  const send = async () => { setSending(true); const res = await base44.functions.invoke("manageParentConversations", { action: "reply", conversation_id: active.id, message: reply, ...credentials }); if (res.data?.success) { setReply(""); open(active); } setSending(false); };
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-slate-900">Parent conversations</h1><p className="mt-1 text-sm text-slate-500">Reply to families and keep every email in one secure thread.</p></div><div className="grid gap-6 lg:grid-cols-[360px_1fr]"><SectionCard title="Conversations"><div className="space-y-2">{conversations.length ? conversations.map((item) => <button key={item.id} onClick={() => open(item)} className={`w-full rounded-xl border p-3 text-left ${active?.id === item.id ? "border-blue-300 bg-blue-50" : "border-slate-200"}`}><div className="flex justify-between gap-2"><p className="font-semibold text-sm text-slate-800">{item.parent_name || item.parent_email}</p>{item.unread_for_teacher && <span className="h-2 w-2 rounded-full bg-blue-600" />}</div><p className="text-xs text-slate-500">{item.student_name} · {item.subject}</p><p className="mt-1 truncate text-xs text-slate-500">{item.last_message_preview}</p></button>) : <p className="py-8 text-center text-sm text-slate-400">No parent conversations yet.</p>}</div></SectionCard><SectionCard title={active ? `${active.parent_name || active.parent_email} · ${active.student_name}` : "Select a conversation"}>{active ? <div className="space-y-4"><div className="max-h-[420px] space-y-3 overflow-y-auto pr-2">{messages.map((item) => <div key={item.id} className={`max-w-[85%] rounded-xl p-3 text-sm ${item.direction === "outbound" ? "ml-auto bg-blue-600 text-white" : "bg-slate-100 text-slate-800"}`}><p className="whitespace-pre-wrap">{item.body}</p><p className={`mt-2 text-xs ${item.direction === "outbound" ? "text-blue-100" : "text-slate-400"}`}>{item.sender_name || item.sender_email} · {new Date(item.sent_at).toLocaleString()}</p></div>)}</div><Textarea value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Write a reply…" /><Button onClick={send} disabled={sending || !reply.trim()}>{sending ? "Sending…" : "Send reply"}</Button></div> : <p className="py-12 text-center text-sm text-slate-400">Choose a conversation to read and reply.</p>}</SectionCard></div></div>;
}