import React from "react";
import LegalLayout from "@/components/legal/LegalLayout";
import FerpaAlignmentVisual from "@/components/security/FerpaAlignmentVisual";

const sections = [
  ["Protecting school information", "ReportAL 360 is designed for schools and districts handling sensitive staff and student information. We use layered safeguards intended to keep data private, secure, and available to authorised users."],
  ["Data access and isolation", "Access is managed by user role and school or district scope. Staff should only be able to view the records and tools needed for their responsibilities, helping to keep information separated between organisations and teams."],
  ["Secure authentication", "The service supports account-based access, multi-factor authentication, and single sign-on where configured. Session controls help protect accounts during use, while administrators can manage access as staff roles change."],
  ["Encryption and infrastructure safeguards", "Information is protected by encrypted connections between your browser and the service. Service credentials and sensitive operations are handled on protected server-side systems rather than exposed in the browser."],
  ["Monitoring and accountability", "Sensitive activity such as viewing student records, changing information, and exporting reports can be recorded in audit logs. These records help schools investigate activity, demonstrate accountability, and support internal oversight."],
  ["Privacy by design", "We apply access controls and minimise exposure of sensitive information in daily workflows. Schools and districts maintain control over their users, permissions, and the information they choose to store in the service."],
  ["Your role in security", "Security is a shared responsibility. Administrators should review access regularly, remove departing staff promptly, and ensure users follow local policies. Users should protect their credentials and report suspected unauthorised activity without delay."],
  ["FERPA: what it requires", "FERPA protects personally identifiable information in education records. It gives parents—and eligible students once rights transfer—the right to inspect and review education records, request correction of records they believe are inaccurate, and control disclosure of personally identifiable information, subject to FERPA’s permitted exceptions."],
  ["FERPA: school responsibilities", "Schools and districts remain responsible for their FERPA programme. This includes providing annual notice of FERPA rights, defining directory information and opt-out procedures, limiting staff access to legitimate educational interests, maintaining appropriate disclosure records where required, and ensuring any third-party service provider is governed by a suitable written agreement and used under district direction."],
  ["How access is protected", "ReportAL 360 uses role and school or district scope to support least-privilege access: users should receive only the data and tools needed for their work. Authentication controls, multi-factor authentication where enabled, account lockouts, password controls, single sign-on options, and activity logging provide additional layers of protection. These technical controls support—but do not replace—district access policies and staff training."],
  ["How information is stored", "Application records are stored in a managed cloud environment, with encryption in transit and at rest and HTTPS used for browser connections. This is not end-to-end encryption: authorised service administrators may be able to access information when needed to operate or support the service. Schools should avoid storing information that is not necessary for the educational purpose and should follow their own retention and deletion policies."],
  ["Data residency, recovery and ownership", "Data is hosted in the United States by default, with regional data-residency options available on certain service plans. Deleted records may be recoverable for a limited period under platform retention controls before permanent deletion. Your school or district remains responsible for the education records it enters, its approved users, retention schedule, and any export or migration requirements in its service agreement."],
  ["Education privacy", "The service is designed to support schools in managing education information responsibly. Each school or district remains responsible for ensuring its use complies with applicable laws, policies, and student privacy obligations, including FERPA where applicable."],
  ["Questions or concerns", "For security or privacy questions, please contact your school or district administrator or the Blueridge Group through the contact details provided with your service agreement."],
];

export default function SecurityPrivacy() {
  return <LegalLayout title="Security & Data Privacy" updated="10 August 2026"><FerpaAlignmentVisual />{sections.map(([heading, text]) => <section key={heading}><h2 className="text-xl font-heading font-semibold text-foreground">{heading}</h2><p className="mt-3">{text}</p></section>)}</LegalLayout>;
}