import React, { useCallback, useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { useSchool } from "@/lib/SchoolContext";
import { Button } from "@/components/ui/button";
import GradeSubmissionDialog from "@/components/assignments/GradeSubmissionDialog";
import LateSubmissionDialog from "@/components/assignments/LateSubmissionDialog";
import { ClipboardCheck, Send, Upload, Users } from "lucide-react";

export default function TeacherAssignmentSubmissions() {
  const { user } = useSchool();
  const [data, setData] = useState({ assignments: [], submissions: [] });
  const [loading, setLoading] = useState(true); const [viewing, setViewing] = useState(null); const [lateUpload, setLateUpload] = useState(null);
  const credentials = { caller_username: user?.username, caller_password: user?.password || localStorage.getItem("userPassword") || "", caller_email: user?.email || "", caller_sso: Boolean(user?.sso || user?.email) };
  const load = useCallback(async () => { if (!user) return; setLoading(true); const response = await base44.functions.invoke("manageAssignments", { action: "teacher_all", ...credentials }); setData({ assignments: response.data?.assignments || [], submissions: response.data?.submissions || [] }); setLoading(false); }, [user]);
  useEffect(() => { load(); }, [load]);
  const release = async (assignment) => { if (!window.confirm(`Release all saved grades for ${assignment.title}?`)) return; await base44.functions.invoke("manageAssignments", { action: "release_grades", assignment_id: assignment.id, ...credentials }); load(); };
  if (loading) return <div className="h-64 animate-pulse rounded-xl bg-slate-100" />;
  return <div className="space-y-6"><div><h2 className="text-lg font-bold text-slate-900">My Assignments</h2><p className="text-sm text-slate-500">Grade submissions, upload late work, and release grades to students.</p></div>{data.assignments.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 py-16 text-center"><ClipboardCheck className="mx-auto mb-3 h-9 w-9 text-slate-300" /><p className="text-sm text-slate-500">You have not created any assignments yet.</p></div> : <div className="space-y-4">{data.assignments.map((assignment) => { const submissions = data.submissions.filter((item) => item.assignment_id === assignment.id); const graded = submissions.filter((item) => item.grade_percentage != null).length; return <section key={assignment.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{assignment.title}</h3><p className="mt-1 text-sm text-slate-500">{assignment.class_name || "Class"} · Due {new Date(assignment.deadline).toLocaleString()}</p></div><div className="flex items-center gap-2"><span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-600"><Users className="h-3.5 w-3.5" />{graded}/{submissions.length} graded</span><Button size="sm" onClick={() => release(assignment)} disabled={!graded}><Send className="h-3.5 w-3.5" />Release grades</Button></div></div><div className="mt-4 divide-y divide-slate-100">{submissions.length ? submissions.map((submission) => <div key={submission.id} className="flex items-center justify-between gap-3 py-3"><button onClick={() => submission.status !== "missing" && setViewing(submission)} className="min-w-0 text-left"><span className="block text-sm font-medium text-slate-800">{submission.student_name}</span><span className={`text-xs font-medium ${submission.status === "missing" ? "text-rose-600" : submission.status === "late" ? "text-amber-600" : "text-slate-500"}`}>{submission.status === "missing" ? "Missing" : submission.status === "late" ? "Late submission" : submission.grade_released ? `${submission.grade_percentage}% released` : submission.grade_percentage != null ? `${submission.grade_percentage}% saved` : "Needs grading"}</span></button>{submission.status === "missing" && <Button size="sm" variant="outline" onClick={() => setLateUpload(submission)}><Upload className="h-3.5 w-3.5" />Upload late work</Button>}</div>) : <p className="py-4 text-sm text-slate-400">No submissions yet.</p>}</div></section>; })}</div>}<GradeSubmissionDialog submission={viewing} credentials={credentials} onClose={() => setViewing(null)} onSaved={load} /><LateSubmissionDialog submission={lateUpload} credentials={credentials} onClose={() => setLateUpload(null)} onSaved={load} /></div>;
}