import React, { useCallback, useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { useSchool } from "@/lib/SchoolContext";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ClipboardCheck, ExternalLink, FileText, Users } from "lucide-react";

export default function TeacherAssignmentSubmissions() {
  const { user } = useSchool();
  const [data, setData] = useState({ assignments: [], submissions: [] });
  const [loading, setLoading] = useState(true);
  const [viewing, setViewing] = useState(null);
  const credentials = { caller_username: user?.username, caller_password: user?.password || localStorage.getItem("userPassword") || "", caller_email: user?.email || "", caller_sso: Boolean(user?.sso || user?.email) };
  const load = useCallback(async () => { if (!user) return; setLoading(true); const response = await base44.functions.invoke("manageAssignments", { action: "teacher_all", ...credentials }); setData({ assignments: response.data?.assignments || [], submissions: response.data?.submissions || [] }); setLoading(false); }, [user]);
  useEffect(() => { load(); }, [load]);
  const openSubmission = async (submission) => { const response = await base44.functions.invoke("manageAssignments", { action: "view_submission", submission_id: submission.id, ...credentials }); setViewing(response.data?.submission || submission); load(); };
  if (loading) return <div className="animate-pulse rounded-xl bg-slate-100 h-64" />;
  return <div className="space-y-6"><div><h2 className="text-lg font-bold text-slate-900">My Assignments</h2><p className="text-sm text-slate-500">Assignments you created and their student submissions.</p></div>{data.assignments.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 py-16 text-center"><ClipboardCheck className="mx-auto mb-3 w-9 h-9 text-slate-300" /><p className="text-sm text-slate-500">You have not created any assignments yet.</p></div> : <div className="space-y-4">{data.assignments.map((assignment) => { const submissions = data.submissions.filter((item) => item.assignment_id === assignment.id); return <section key={assignment.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{assignment.title}</h3><p className="mt-1 text-sm text-slate-500">{assignment.class_name || "Class"} · Due {new Date(assignment.deadline).toLocaleString()}</p></div><span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-600"><Users className="w-3.5 h-3.5" />{submissions.length} submitted</span></div><div className="mt-4 divide-y divide-slate-100">{submissions.length ? submissions.map((submission) => <button key={submission.id} onClick={() => openSubmission(submission)} className="flex w-full items-center justify-between gap-3 py-3 text-left hover:bg-slate-50"><span className="text-sm font-medium text-slate-800">{submission.student_name}</span><span className="text-xs text-slate-500">{submission.status === "viewed" ? "Viewed" : "New"} · {new Date(submission.submitted_at).toLocaleString()}</span></button>) : <p className="py-4 text-sm text-slate-400">No submissions yet.</p>}</div></section>; })}</div>}<Dialog open={!!viewing} onOpenChange={(open) => !open && setViewing(null)}><DialogContent><DialogHeader><DialogTitle>{viewing?.student_name}'s submission</DialogTitle></DialogHeader><div className="space-y-3 text-sm"><p>AI similarity score: <strong>{viewing?.plagiarism_score == null ? "Unavailable" : `${viewing.plagiarism_score}%`}</strong></p>{viewing?.plagiarism_note && <p className="text-slate-600">{viewing.plagiarism_note}</p>}{viewing?.submission_text && <p className="whitespace-pre-wrap rounded-lg bg-slate-50 p-3">{viewing.submission_text}</p>}{viewing?.file_url && <Button asChild variant="outline"><a href={viewing.file_url} target="_blank" rel="noreferrer"><FileText className="w-4 h-4" />Open uploaded document <ExternalLink className="w-3.5 h-3.5" /></a></Button>}</div></DialogContent></Dialog></div>;
}