import React, { useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Settings } from "lucide-react";

const permissions = [{ id: "school_access", label: "Access schools" }, { id: "audit_access", label: "Run and view audits" }, { id: "school_discovery", label: "Manage school directory" }, { id: "admin_management", label: "Manage administrators" }];
export default function AdminManagementDialog({ admin, callerCreds, onUpdated }) {
  const initial = admin.admin_permissions || permissions.map((item) => item.id); const [open, setOpen] = useState(false); const [fullName, setFullName] = useState(admin.full_name); const [email, setEmail] = useState(admin.email?.endsWith("@local.reportal360") ? "" : admin.email || ""); const [selected, setSelected] = useState(initial); const [newPassword, setNewPassword] = useState(""); const [activity, setActivity] = useState([]); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (open) base44.functions.invoke("manageSchoolStaff", { action: "list_admin_activity", ...callerCreds, username: admin.username }).then((res) => setActivity(res.data?.activity || [])); }, [open]);
  const toggle = (id) => setSelected(selected.includes(id) ? selected.filter((item) => item !== id) : [...selected, id]);
  const save = async () => { setSaving(true); setError(""); const res = await base44.functions.invoke("manageSchoolStaff", { action: "update_platform_admin", ...callerCreds, user_id: admin.id, full_name: fullName, email, admin_permissions: selected }); if (res.data?.success) onUpdated(); else setError(res.data?.error || "Unable to save administrator"); setSaving(false); };
  const reset = async () => { setSaving(true); setError(""); const res = await base44.functions.invoke("manageSchoolStaff", { action: "reset_platform_admin_password", ...callerCreds, user_id: admin.id, password: newPassword }); if (res.data?.success) setNewPassword(""); else setError(res.data?.error || "Unable to reset password"); setSaving(false); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button type="button" size="sm" variant="outline"><Settings className="h-3.5 w-3.5" />Manage</Button></DialogTrigger><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Manage {admin.username}</DialogTitle></DialogHeader><div className="grid gap-4 md:grid-cols-2"><div><Label>Full name</Label><Input value={fullName} onChange={(event) => setFullName(event.target.value)} className="mt-1" /></div><div><Label>SSO email address</Label><Input type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1" /></div></div><div><Label>Administrator permissions</Label><div className="mt-2 grid gap-2 md:grid-cols-2">{permissions.map((item) => <label key={item.id} className="flex items-center gap-2 rounded-md border border-slate-200 p-2 text-sm"><Checkbox checked={selected.includes(item.id)} onCheckedChange={() => toggle(item.id)} />{item.label}</label>)}</div></div><Button type="button" disabled={saving} onClick={save}>{saving ? "Saving..." : "Save changes"}</Button><div className="border-t pt-4"><Label>Reset password</Label><div className="mt-1 flex gap-2"><Input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} placeholder="New temporary password" /><Button type="button" variant="outline" disabled={!newPassword || saving} onClick={reset}>Reset password</Button></div></div>{error && <p className="text-sm text-rose-600">{error}</p>}<div className="border-t pt-4"><Label>Recent activity</Label><div className="mt-2 max-h-36 space-y-2 overflow-auto">{activity.length ? activity.map((item) => <div key={item.id} className="rounded bg-slate-50 p-2 text-xs text-slate-600"><strong>{item.action_type || item.event_type}</strong> · {item.details}<span className="ml-1 text-slate-400">{new Date(item.created_date).toLocaleString()}</span></div>) : <p className="text-sm text-slate-400">No activity recorded.</p>}</div></div></DialogContent></Dialog>;
}