import React from "react";
import { Link } from "react-router-dom";
import { Bell, AlertCircle, CheckCircle2, ClipboardCheck, MessageSquare } from "lucide-react";
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover";
import { useNotifications } from "@/lib/useNotifications";

const CRIMSON = "#9E1B32";

export default function NotificationBell() {
  const { items, loading, count } = useNotifications();
  return <Popover><PopoverTrigger asChild><button type="button" className="relative rounded-lg p-2 text-white/70 transition-colors hover:bg-white/10 hover:text-white" title="Notifications"><Bell className="h-5 w-5" />{!loading && count > 0 && <span className="absolute -right-0.5 -top-0.5 flex h-[18px] min-w-[18px] items-center justify-center rounded-full px-1 text-[10px] font-bold text-white ring-2 ring-[#0B1530]" style={{ backgroundColor: CRIMSON }}>{count > 9 ? "9+" : count}</span>}</button></PopoverTrigger><PopoverContent align="end" className="w-[360px] max-w-[calc(100vw-2rem)] p-0" sideOffset={8}><div className="border-b border-slate-100 px-4 py-3"><p className="text-sm font-semibold text-slate-900">Notifications</p><p className="text-xs text-slate-500">Unread staff messages and attendance reminders</p></div><div className="max-h-[60vh] overflow-y-auto">{loading ? <div className="space-y-3 p-4">{[1, 2, 3].map((item) => <div key={item} className="h-14 animate-pulse rounded-lg bg-slate-100" />)}</div> : count === 0 ? <div className="px-4 py-10 text-center"><CheckCircle2 className="mx-auto mb-2 h-8 w-8 text-emerald-500" /><p className="text-sm font-medium text-slate-700">You're all caught up</p></div> : <div className="space-y-1 p-2">{items.map((notification) => <div key={notification.id} className="flex items-start gap-3 rounded-lg p-3 hover:bg-slate-50"><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${notification.type === "message" ? "bg-blue-50" : "bg-amber-50"}`}>{notification.type === "message" ? <MessageSquare className="h-4 w-4 text-blue-600" /> : <AlertCircle className="h-4 w-4 text-amber-500" />}</div><div className="min-w-0 flex-1"><p className="text-sm font-semibold leading-tight text-slate-900">{notification.title}</p><p className="mt-0.5 line-clamp-2 text-xs text-slate-500">{notification.detail}</p></div><Link to={notification.type === "message" ? "/messages" : `/classes/${notification.class_id}`} className="inline-flex shrink-0 items-center gap-1 rounded-lg bg-slate-900 px-2.5 py-1.5 text-xs font-medium text-white hover:bg-slate-800">{notification.type === "message" ? <MessageSquare className="h-3.5 w-3.5" /> : <ClipboardCheck className="h-3.5 w-3.5" />}</Link></div>)}</div>}</div></PopoverContent></Popover>;
}