import React, { useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export default function SchoolAccessAuthorizationDialog({ open, onOpenChange, callerCreds, schoolKey, reason, onApproved }) {
  const [staff, setStaff] = useState([]); const [staffId, setStaffId] = useState(""); const [challengeId, setChallengeId] = useState(""); const [code, setCode] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (open) { setChallengeId(""); setCode(""); setError(""); base44.functions.invoke("manageSchoolStaff", { action: "list_school_access_authorizers", ...callerCreds, school_key: schoolKey }).then((res) => setStaff(res.data?.staff || [])); } }, [open, schoolKey]);
  const sendCode = async () => { setLoading(true); setError(""); const res = await base44.functions.invoke("manageSchoolStaff", { action: "request_school_access_authorization", ...callerCreds, school_key: schoolKey, reason, authorizer_id: staffId }); if (!res.data?.success) setError(res.data?.error || "Unable to send the authorization code"); else setChallengeId(res.data.challenge_id); setLoading(false); };
  const verifyCode = async () => { setLoading(true); setError(""); const res = await base44.functions.invoke("manageSchoolStaff", { action: "verify_school_access_authorization", ...callerCreds, challenge_id: challengeId, authorization_code: code }); if (!res.data?.success) setError(res.data?.error || "Authorization code could not be verified"); else onApproved(res.data.school); setLoading(false); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>School staff authorization required</DialogTitle></DialogHeader>{challengeId ? <div className="space-y-4"><p className="text-sm text-slate-600">The selected staff member has received a three-word authorization code. Enter the words exactly as provided.</p><div><Label>Authorization code</Label><Input value={code} onChange={(event) => setCode(event.target.value)} placeholder="three words here" className="mt-1" /></div>{error && <p className="text-sm text-rose-600">{error}</p>}<Button onClick={verifyCode} disabled={!code.trim() || loading}>{loading ? "Verifying..." : "Verify and access school"}</Button></div> : <div className="space-y-4"><p className="text-sm text-slate-600">Select a staff member at this school. They will receive a three-word code to authorize your access.</p><div><Label>Authorizing staff member</Label><select value={staffId} onChange={(event) => setStaffId(event.target.value)} className="mt-1 flex h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm"><option value="">Select staff member</option>{staff.map((member) => <option key={member.id} value={member.id}>{member.full_name} · {member.email}</option>)}</select></div>{error && <p className="text-sm text-rose-600">{error}</p>}<Button onClick={sendCode} disabled={!staffId || loading}>{loading ? "Sending..." : "Send authorization code"}</Button></div>}</DialogContent></Dialog>;
}