import React, { useEffect, useState } from "react";
import { ArrowRightLeft } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export default function StudentTransferDialog({ schoolCode, selectedStudents, credentials, onComplete }) {
  const [open, setOpen] = useState(false); const [schools, setSchools] = useState([]); const [target, setTarget] = useState(""); const [grade, setGrade] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!open) return; base44.functions.invoke("manageStudents", { action: "list_transfer_destinations", ...credentials }).then((res) => setSchools((res.data?.schools || []).filter((school) => school.school_code !== schoolCode))); }, [open, schoolCode]);
  const transfer = async () => { setSaving(true); setError(""); const res = await base44.functions.invoke("manageStudents", { action: "transfer", ...credentials, school_code: schoolCode, target_school_code: target, student_ids: selectedStudents.map((student) => student.id), grade_level: grade }); if (!res.data?.success) { setError(res.data?.error || "Transfer failed"); setSaving(false); return; } setOpen(false); setTarget(""); setGrade(""); setSaving(false); onComplete(); };
  return <Dialog open={open} onOpenChange={setOpen}><Button disabled={!selectedStudents.length} onClick={() => setOpen(true)} variant="outline"><ArrowRightLeft className="mr-2 h-4 w-4" />Transfer selected ({selectedStudents.length})</Button><DialogContent><DialogHeader><DialogTitle>Transfer students</DialogTitle></DialogHeader><p className="text-sm text-slate-600">Transfer {selectedStudents.length} selected student{selectedStudents.length === 1 ? "" : "s"}. Their account and academic history will remain linked to the same student record.</p><select value={target} onChange={(event) => setTarget(event.target.value)} className="w-full rounded-md border border-slate-200 px-3 py-2 text-sm"><option value="">Choose destination school</option>{schools.map((school) => <option key={school.school_code} value={school.school_code}>{school.school_name} ({school.school_code})</option>)}</select><select value={grade} onChange={(event) => setGrade(event.target.value)} className="w-full rounded-md border border-slate-200 px-3 py-2 text-sm"><option value="">Keep current grade</option>{["K", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"].map((value) => <option key={value} value={value}>Grade {value}</option>)}</select>{error && <p className="text-sm text-rose-600">{error}</p>}<Button disabled={!target || saving} onClick={transfer}>{saving ? "Transferring…" : "Confirm transfer"}</Button></DialogContent></Dialog>;
}