import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export default function SupportRequestItem({ request, callerCreds, teamsConnected, onConnectTeams }) {
  const [detail, setDetail] = useState(null), [reply, setReply] = useState(""), [startAt, setStartAt] = useState(""), [loading, setLoading] = useState(false), [notice, setNotice] = useState("");
  const loadDetail = async () => { setLoading(true); const result = await base44.functions.invoke("manageStaffMessages", { action: "support_request_detail", request_id: request.id, ...callerCreds }); setDetail(result.data); setLoading(false); };
  const sendReply = async () => { setLoading(true); const result = await base44.functions.invoke("manageStaffMessages", { action: "support_reply", request_id: request.id, content: reply, ...callerCreds }); setNotice(result.data?.success ? "Reply sent." : result.data?.error || "Unable to send reply."); if (result.data?.success) setReply(""); setLoading(false); };
  const createMeeting = async () => { setLoading(true); const endAt = new Date(new Date(startAt).getTime() + 30 * 60000).toISOString(); const result = await base44.functions.invoke("manageStaffMessages", { action: "create_support_meeting", request_id: request.id, start_at: new Date(startAt).toISOString(), end_at: endAt, ...callerCreds }); setNotice(result.data?.success ? "Teams meeting created and sent to the teacher." : result.data?.error || "Unable to create the meeting."); setLoading(false); };
  return <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold text-slate-900">{request.sender_name}</p><p className="text-xs text-slate-500">{request.system_code ? `${request.system_code} · ` : ""}{request.school_code} · {new Date(request.created_date).toLocaleString()}</p></div><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{request.content}</p><p className="mt-2 text-xs text-slate-500">Reported from: {request.current_path || "Unknown screen"}</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={loadDetail} disabled={loading}>View availability</Button><Button size="sm" variant="outline" onClick={() => window.location.assign(`/admin?school=${encodeURIComponent(request.school_code)}`)}>Access school system</Button></div>{detail?.success && <div className="mt-3 rounded-lg border border-slate-200 bg-white p-3"><p className="text-sm font-medium text-slate-900">{detail.teacher.full_name}'s teaching schedule</p><div className="mt-2 space-y-1 text-xs text-slate-600">{detail.schedule.length ? detail.schedule.map((slot) => <p key={slot.id}>{slot.day_of_week} · {slot.start_time}–{slot.end_time} · {slot.class_name || slot.period_label || "Teaching"}</p>) : <p>No scheduled teaching blocks are available.</p>}</div><Textarea value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Reply to this teacher…" className="mt-3 min-h-16" /><Button size="sm" className="mt-2" onClick={sendReply} disabled={loading || !reply.trim()}>Send reply</Button><div className="mt-4 border-t border-slate-100 pt-3"><p className="text-xs font-medium text-slate-700">Arrange a Microsoft Teams call</p>{teamsConnected ? <div className="mt-2 flex flex-wrap items-center gap-2"><Input type="datetime-local" value={startAt} onChange={(event) => setStartAt(event.target.value)} className="w-auto" /><Button size="sm" onClick={createMeeting} disabled={loading || !startAt}>Create 30-minute call</Button></div> : <Button size="sm" variant="outline" className="mt-2" onClick={onConnectTeams}>Connect Microsoft Teams</Button>}</div></div>}{notice && <p className="mt-3 text-xs text-slate-600">{notice}</p>}</div>;
}