import React, { useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

const remaining = (due) => {
  if (!due) return "No SLA set";
  const seconds = Math.ceil((new Date(due).getTime() - Date.now()) / 1000);
  if (seconds <= 0) return "SLA overdue";
  return `${Math.floor(seconds / 3600)}h ${Math.floor((seconds % 3600) / 60)}m remaining`;
};

export default function SupportRequestItem({ request, administrators, callerCreds, outlookConnected, onConnectOutlook, onUpdated }) {
  const [detail, setDetail] = useState(null), [reply, setReply] = useState(""), [startAt, setStartAt] = useState(""), [loading, setLoading] = useState(false), [notice, setNotice] = useState(""), [clock, setClock] = useState(0);
  useEffect(() => { const timer = setInterval(() => setClock((value) => value + 1), 60000); return () => clearInterval(timer); }, []);
  const loadDetail = async () => { setLoading(true); const result = await base44.functions.invoke("manageStaffMessages", { action: "support_request_detail", request_id: request.id, ...callerCreds }); setDetail(result.data); setLoading(false); };
  const sendReply = async () => { setLoading(true); const result = await base44.functions.invoke("manageStaffMessages", { action: "support_reply", request_id: request.id, content: reply, ...callerCreds }); setNotice(result.data?.success ? "Reply sent." : result.data?.error || "Unable to send reply."); if (result.data?.success) setReply(""); setLoading(false); };
  const reassign = async (adminId) => { if (!adminId) return; setLoading(true); const result = await base44.functions.invoke("manageStaffMessages", { action: "reassign_support_request", request_id: request.id, admin_id: adminId, ...callerCreds }); setNotice(result.data?.success ? "Ticket reassigned." : result.data?.error || "Unable to reassign ticket."); setLoading(false); if (result.data?.success) onUpdated(); };
  const createMeeting = async () => { setLoading(true); const endAt = new Date(new Date(startAt).getTime() + 30 * 60000).toISOString(); const result = await base44.functions.invoke("manageStaffMessages", { action: "create_support_meeting", request_id: request.id, start_at: new Date(startAt).toISOString(), end_at: endAt, ...callerCreds }); setNotice(result.data?.success ? "Outlook appointment created, emailed to both attendees, and added to the teacher's schedule." : result.data?.error || "Unable to create the appointment."); setLoading(false); };
  const overdue = request.sla_due_at && new Date(request.sla_due_at) <= new Date();
  return <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold text-slate-900">{request.sender_name}</p><p className={`text-xs font-semibold ${overdue ? "text-rose-700" : "text-amber-700"}`}>{remaining(request.sla_due_at)}{clock < 0 ? "" : ""}</p></div><p className="mt-1 text-xs text-slate-500">{request.system_code ? `${request.system_code} · ` : ""}{request.school_code} · {new Date(request.created_date).toLocaleString()}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{request.content}</p><p className="mt-2 text-xs text-slate-500">Reported from: {request.current_path || "Unknown screen"}</p><div className="mt-3 grid gap-2 md:grid-cols-2"><div><label className="text-xs font-medium text-slate-600">Assigned administrator</label><select value={request.assigned_admin_id || ""} onChange={(event) => reassign(event.target.value)} disabled={loading} className="mt-1 h-9 w-full rounded-md border border-slate-200 bg-white px-2 text-sm"><option value="">Select administrator</option>{administrators.map((admin) => <option key={admin.id} value={admin.id}>{admin.full_name} · {admin.expertise} · {admin.workload} open</option>)}</select></div><div className="flex items-end gap-2"><Button size="sm" variant="outline" onClick={loadDetail} disabled={loading}>View availability</Button><Button size="sm" variant="outline" onClick={() => window.location.assign(`/admin/access?school=${encodeURIComponent(request.school_code)}`)}>Access school</Button></div></div>{detail?.success && <div className="mt-3 rounded-lg border border-slate-200 bg-white p-3"><p className="text-sm font-medium text-slate-900">{detail.teacher.full_name}'s teaching schedule</p><div className="mt-2 space-y-1 text-xs text-slate-600">{detail.schedule.length ? detail.schedule.map((slot) => <p key={slot.id}>{slot.day_of_week} · {slot.start_time}–{slot.end_time} · {slot.class_name || slot.period_label || "Teaching"}</p>) : <p>No scheduled teaching blocks are available.</p>}</div><Textarea value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Reply to this teacher…" className="mt-3 min-h-16" /><Button size="sm" className="mt-2" onClick={sendReply} disabled={loading || !reply.trim()}>Send reply</Button><div className="mt-4 border-t border-slate-100 pt-3"><p className="text-xs font-medium text-slate-700">Arrange a support appointment</p>{outlookConnected ? <div className="mt-2 flex flex-wrap items-center gap-2"><Input type="datetime-local" value={startAt} onChange={(event) => setStartAt(event.target.value)} className="w-auto" /><Button size="sm" onClick={createMeeting} disabled={loading || !startAt}>Create 30-minute call</Button></div> : <Button size="sm" variant="outline" className="mt-2" onClick={onConnectOutlook}>Connect Outlook Calendar</Button>}</div></div>}{notice && <p className="mt-3 text-xs text-slate-600">{notice}</p>}</div>;
}