import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export default function AthleticsRosterManager({ team, students, members, schoolCode, onAdded }) {
  const [open, setOpen] = useState(false); const [selected, setSelected] = useState([]); const [grades, setGrades] = useState([]); const [gender, setGender] = useState(""); const [saving, setSaving] = useState(false);
  const roster = members.filter((member) => member.team_id === team.id);
  const available = students.filter((student) => !roster.some((member) => member.student_id === student.id));
  const gradeLevels = [...new Set(available.map((student) => student.grade_level).filter(Boolean))].sort();
  const filtered = available.filter((student) => (!grades.length || grades.includes(student.grade_level)) && (!gender || student.gender === gender));
  const toggle = (id) => setSelected((ids) => ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id]);
  const toggleGrade = (grade) => setGrades((items) => items.includes(grade) ? items.filter((item) => item !== grade) : [...items, grade]);
  const add = async () => { const newMembers = available.filter((student) => selected.includes(student.id)).map((student) => ({ school_code: schoolCode, team_id: team.id, student_id: student.id, student_name: student.student_name, grade_level: student.grade_level || "" })); if (!newMembers.length) return; setSaving(true); const created = await base44.entities.AthleticsTeamMember.bulkCreate(newMembers); setSaving(false); setSelected([]); setOpen(false); onAdded(created); };
  return <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold text-slate-900">{team.name}</h3><p className="text-xs text-slate-500">{team.sport} · Coach {team.coach_name}</p></div><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-medium text-blue-700">{roster.length} athletes</span></div><Button size="sm" variant="outline" className="mt-3" onClick={() => setOpen(true)}>Add athletes</Button>{roster.length > 0 && <p className="mt-3 text-sm text-slate-600">{roster.map((member) => member.student_name).join(", ")}</p>}<Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Add athletes to {team.name}</DialogTitle><DialogDescription>Filter students, then select everyone who should join this roster.</DialogDescription></DialogHeader><div className="space-y-3"><div className="rounded-lg bg-slate-50 p-3"><p className="mb-2 text-xs font-medium text-slate-600">Grade level</p><div className="flex flex-wrap gap-3">{gradeLevels.map((grade) => <label key={grade} className="flex cursor-pointer items-center gap-2 text-sm text-slate-700"><Checkbox checked={grades.includes(grade)} onCheckedChange={() => toggleGrade(grade)} />{grade}</label>)}</div></div><select value={gender} onChange={(event) => setGender(event.target.value)} className="h-9 w-full rounded-md border border-input bg-white px-3 text-sm"><option value="">All genders</option><option value="Male">Male</option><option value="Female">Female</option></select><div className="max-h-64 space-y-2 overflow-y-auto">{filtered.map((student) => <label key={student.id} className="flex cursor-pointer items-center gap-3 rounded-lg px-2 py-2 hover:bg-slate-50"><Checkbox checked={selected.includes(student.id)} onCheckedChange={() => toggle(student.id)} /><span className="text-sm text-slate-700">{student.student_name} {student.grade_level ? <span className="text-slate-400">· {student.grade_level}</span> : null}</span></label>)}{!filtered.length && <p className="text-sm text-slate-500">No students match these filters.</p>}</div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={!selected.length || saving} onClick={add}>{saving ? "Adding..." : `Add ${selected.length || ""} athlete${selected.length === 1 ? "" : "s"}`}</Button></DialogFooter></DialogContent></Dialog></div>;
}